# Generated by Django 4.1.7 on 2023-03-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_image_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
